// Protocol messages for describing the results of benchmarks and unit tests.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.11
// source: tensorflow/core/util/test_log.proto

package test_log_proto_go_proto

import (
	for_core_protos_go_proto "github.com/wamuir/graft/tensorflow/tsl/protobuf/for_core_protos_go_proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Symbols defined in public import of tensorflow/tsl/protobuf/test_log.proto.

type TestResults_BenchmarkType = for_core_protos_go_proto.TestResults_BenchmarkType

const TestResults_UNKNOWN = for_core_protos_go_proto.TestResults_UNKNOWN
const TestResults_CPP_MICROBENCHMARK = for_core_protos_go_proto.TestResults_CPP_MICROBENCHMARK
const TestResults_PYTHON_BENCHMARK = for_core_protos_go_proto.TestResults_PYTHON_BENCHMARK
const TestResults_ANDROID_BENCHMARK = for_core_protos_go_proto.TestResults_ANDROID_BENCHMARK
const TestResults_EDGE_BENCHMARK = for_core_protos_go_proto.TestResults_EDGE_BENCHMARK
const TestResults_IOS_BENCHMARK = for_core_protos_go_proto.TestResults_IOS_BENCHMARK

var TestResults_BenchmarkType_name = for_core_protos_go_proto.TestResults_BenchmarkType_name
var TestResults_BenchmarkType_value = for_core_protos_go_proto.TestResults_BenchmarkType_value

type EntryValue = for_core_protos_go_proto.EntryValue
type EntryValue_DoubleValue = for_core_protos_go_proto.EntryValue_DoubleValue
type EntryValue_StringValue = for_core_protos_go_proto.EntryValue_StringValue
type MetricEntry = for_core_protos_go_proto.MetricEntry
type BenchmarkEntry = for_core_protos_go_proto.BenchmarkEntry
type BenchmarkEntries = for_core_protos_go_proto.BenchmarkEntries
type BuildConfiguration = for_core_protos_go_proto.BuildConfiguration
type CommitId = for_core_protos_go_proto.CommitId
type CommitId_Changelist = for_core_protos_go_proto.CommitId_Changelist
type CommitId_Hash = for_core_protos_go_proto.CommitId_Hash
type CPUInfo = for_core_protos_go_proto.CPUInfo
type MemoryInfo = for_core_protos_go_proto.MemoryInfo
type GPUInfo = for_core_protos_go_proto.GPUInfo
type PlatformInfo = for_core_protos_go_proto.PlatformInfo
type AvailableDeviceInfo = for_core_protos_go_proto.AvailableDeviceInfo
type MachineConfiguration = for_core_protos_go_proto.MachineConfiguration
type RunConfiguration = for_core_protos_go_proto.RunConfiguration
type TestResults = for_core_protos_go_proto.TestResults

var File_tensorflow_core_util_test_log_proto protoreflect.FileDescriptor

var file_tensorflow_core_util_test_log_proto_rawDesc = []byte{
	0x0a, 0x23, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x63, 0x6f, 0x72,
	0x65, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f,
	0x77, 0x2e, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x1a, 0x26, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66,
	0x6c, 0x6f, 0x77, 0x2f, 0x74, 0x73, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42,
	0x52, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66,
	0x6c, 0x6f, 0x77, 0x2f, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x67,
	0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x2f, 0x74, 0x65, 0x73, 0x74,
	0x5f, 0x6c, 0x6f, 0x67, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x6f, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_tensorflow_core_util_test_log_proto_goTypes = []interface{}{}
var file_tensorflow_core_util_test_log_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tensorflow_core_util_test_log_proto_init() }
func file_tensorflow_core_util_test_log_proto_init() {
	if File_tensorflow_core_util_test_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tensorflow_core_util_test_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tensorflow_core_util_test_log_proto_goTypes,
		DependencyIndexes: file_tensorflow_core_util_test_log_proto_depIdxs,
	}.Build()
	File_tensorflow_core_util_test_log_proto = out.File
	file_tensorflow_core_util_test_log_proto_rawDesc = nil
	file_tensorflow_core_util_test_log_proto_goTypes = nil
	file_tensorflow_core_util_test_log_proto_depIdxs = nil
}
