package(default_visibility = ["//visibility:private"])

alias(
    name = "libtensorflow_proto",
    actual = "//third_party/org_tensorflow:libtensorflow_proto",
    visibility = ["//visibility:public"],
)

alias(
    name = "libtensorflow",
    actual = "//third_party/org_tensorflow:libtensorflow_pkg",
    visibility = ["//visibility:public"],
)
