package(default_visibility = ["//visibility:private"])

config_setting(
    name = "linux_x86_64_cpu",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
        "//tools/platforms/device:cpu",
    ],
)

config_setting(
    name = "linux_x86_64_gpu",
    constraint_values = [
        "@platforms//os:linux",
        "@platforms//cpu:x86_64",
        "//tools/platforms/device:gpu",
    ],
)

config_setting(
    name = "macos_x86_64_cpu",
    constraint_values = [
        "@platforms//os:macos",
        "@platforms//cpu:x86_64",
        "//tools/platforms/device:cpu",
    ],
)

config_setting(
    name = "windows_x86_64_cpu",
    constraint_values = [
        "@platforms//os:windows",
        "@platforms//cpu:x86_64",
        "//tools/platforms/device:cpu",
    ],
)

config_setting(
    name = "windows_x86_64_gpu",
    constraint_values = [
        "@platforms//os:windows",
        "@platforms//cpu:x86_64",
        "//tools/platforms/device:gpu",
    ],
)
