---
name: test

on:
  push:
    branches:
      - 'main'
      - 'r[0-9]+.[0-9]+'
  pull_request:
    branches:
      - 'main'
      - 'r[0-9]+.[0-9]+'
  workflow_dispatch:

env:
  USE_BAZEL_VERSION: "latest"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1

      - name: Log Bazel version
        run: bazelisk version

      - name: Test
        run: bazelisk test --config=ci -- //...

      - name: Build Go bindings
        run: bazelisk build --config=ci -- //tools/graft_package:go_bindings

      - name: Archive Go bindings
        uses: actions/upload-artifact@v2
        with:
          name: go_bindings
          path: bazel-bin/tools/graft_package/go_bindings.tar.gz
          retention-days: 3

  test:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1

      - name: Download go_bindings
        uses: actions/download-artifact@v2
        with:
          name: go_bindings

      - name: Update bindings
        run: |
          rm -rf tensorflow
          tar xz --strip-components=5 \
            -f go_bindings.tar.gz \
            ./src/github.com/wamuir/graft/tensorflow
          rm go_bindings.tar.gz

      - name: Run gazelle
        run: |
          bazelisk run //:gazelle
          bazelisk run //:gazelle-update-repos

      - name: Test bindings
        run: bazelisk test --config=ci -- //tensorflow/...
